// <auto-generated />
using System;
using LocadoraApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocadoraApi.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20250404222129_Ajustes")]
    partial class Ajustes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentificadorCarro")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("ReferenciaModeloCodigo")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.HasIndex("ReferenciaModeloCodigo");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdentificadorCarroCodigo")
                        .HasColumnType("integer");

                    b.Property<int>("IdentificadorUsuarioCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Codigo");

                    b.HasIndex("IdentificadorCarroCodigo");

                    b.HasIndex("IdentificadorUsuarioCodigo");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Marca", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenciaMarcaCodigo")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.HasIndex("ReferenciaMarcaCodigo");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentificadorUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Modelo", "ReferenciaModelo")
                        .WithMany()
                        .HasForeignKey("ReferenciaModeloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenciaModelo");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Carro", "IdentificadorCarro")
                        .WithMany()
                        .HasForeignKey("IdentificadorCarroCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocadoraApi.Domain.Usuario", "IdentificadorUsuario")
                        .WithMany()
                        .HasForeignKey("IdentificadorUsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentificadorCarro");

                    b.Navigation("IdentificadorUsuario");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Marca", "ReferenciaMarca")
                        .WithMany()
                        .HasForeignKey("ReferenciaMarcaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenciaMarca");
                });
#pragma warning restore 612, 618
        }
    }
}
