// <auto-generated />
using System;
using LocadoraApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocadoraApi.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20250413222552_ControllersFinalizados")]
    partial class ControllersFinalizados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoCarro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentificadorCarro")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("ReferenciaModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.HasIndex("ReferenciaModeloId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdentificadorCarroId")
                        .HasColumnType("integer");

                    b.Property<int>("IdentificadorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("IdentificadorCarroId");

                    b.HasIndex("IdentificadorUsuarioId");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Marca", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("NomeMarca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReferenciaMarcaId")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.HasIndex("ReferenciaMarcaId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentificadorUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Modelo", "ReferenciaModelo")
                        .WithMany()
                        .HasForeignKey("ReferenciaModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferenciaModelo");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Carro", "IdentificadorCarro")
                        .WithMany()
                        .HasForeignKey("IdentificadorCarroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocadoraApi.Domain.Usuario", "IdentificadorUsuario")
                        .WithMany()
                        .HasForeignKey("IdentificadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentificadorCarro");

                    b.Navigation("IdentificadorUsuario");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Marca", "ReferenciaMarca")
                        .WithMany()
                        .HasForeignKey("ReferenciaMarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferenciaMarca");
                });
#pragma warning restore 612, 618
        }
    }
}
