// <auto-generated />
using System;
using LocadoraApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocadoraApi.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20250402191634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoModelo")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoModelo");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CodigoCarro")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoUsuario")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCarro");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Marca", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CodigoMarca")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoMarca");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Modelo", "Modelo")
                        .WithMany("Carros")
                        .HasForeignKey("CodigoModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Locacao", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Carro", "Carro")
                        .WithMany("Locacoes")
                        .HasForeignKey("CodigoCarro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocadoraApi.Domain.Usuario", "Usuario")
                        .WithMany("Locacoes")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.HasOne("LocadoraApi.Domain.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("CodigoMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Carro", b =>
                {
                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Modelo", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("LocadoraApi.Domain.Usuario", b =>
                {
                    b.Navigation("Locacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
